### ISSUE TITLE
Data omitted if not in first row of XLS

### ISSUE THREAD

**Issue by pluby** [vweevers/tabular-stream#2]
Using an XLS file (not a CSV), if columns are missing from the first data row (second row) then you only get the data on subsequent rows for the columns present in the first data row.

Consider the following, but saved as an XLS file:

```
A,B,C
1,,
1,2,3
4,5,6
```

You get:

```
{ A: 1 }
{ A: 1 }
{ A: 4 }
```

Using `detect-tabular` instead you get:

```
{ A: 1 }
{ A: 1, B: 2, C: 3 }
{ A: 4, B: 5, C: 6 }
```

Reading a CSV file gives you:

```
{ A: 1, B: 0, C: 0 }
{ A: 1, B: 2, C: 3 }
{ A: 4, B: 5, C: 6 }
```

Ignore the issue with the zeros.

It may be that the underlying Excel reader could be considered faulty and should emit consistent objects with null values for missing data, but I'm not sufficiently familiar with it all to make a judgement.

Test code that I used:

```
var tabular = require("tabular-stream"); // or "detect-tabular" for comparison.
var fs = require("fs");
var stream = tabular();
stream.on("data", console.log);
stream.end(fs.readFileSync(__dirname+"/test.xls"));
```

**Comment by vweevers** [comment]
I think the issue is in `map-tabular-keys`, which only [reads the keys of the first row](https://github.com/vweevers/map-tabular-keys/blob/master/index.js#L30) and uses that set of keys for all following rows.

**Comment by pluby** [comment]
Perhaps also an issue with the Excel reader, whatever that is, not providing keys for all columns regardless of presence?

I'm not sure what change could be made to `map-tabular-keys` to make it work like the CSV version and give us all keys up-front.

**Comment by vweevers** [comment]
@pluby `detect-tabular` uses `excel-stream` which  uses `j`. You could try the `j` [cli](https://github.com/SheetJS/j#cli-tool) or API directly, see what it does with your xls.
